# Generated by Django 5.2.9 on 2025-12-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_images_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='max_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='max_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='min_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='min_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
