# Generated by Django 5.2.9 on 2025-12-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_images_max_lat_images_max_lon_images_min_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='png',
            field=models.FileField(blank=True, null=True, upload_to='images/png/'),
        ),
    ]
